FIO-7615: Add option to migrate pdf files to copy and migrate commands
formio/cli pull request #79
Opened 2024-11-14 10:04 UTC by mikekotikov

2025-02-19 23:05 UTC, brendanbond requested changes

2025-02-19 23:05 UTC, brendanbond commented on src/copy.js
> +        }).then(async({body: form}) => {
This is a minor issue but I don't love mixing modalities here - can we either use all async/await or stick with promise chaining here? I think if it were me I'd stick with promise chaining, because refactoring this file (and potentially others) to async/await would be a lot of work, whereas it's relatively clean and easy to use promise chaining here

2025-02-21 09:46 UTC, mikekotikov commented on src/copy.js
> +        }).then(async({body: form}) => {
Done

2025-02-25 13:27 UTC, brendanbond approved these changes

2025-02-25 13:27 UTC, merged